### PR TITLE
Added Custom Hooks, Included State Reducer, encapsulated code.

### PR DESCRIPTION
**Pull request by abhik-99**
Have only touched the `pages/index.js` file as instructed. Did not touch the `components` directory. The minor change was all that was done in the `components/Dashboard.js` during the call.

### CODE REVIEW

**Comment by aditya172926** [comment]
I am getting some errors in your fork @abhik-99 . Check this 

First is this UI issue - it wasn't there previously
image

Second - this happens when I click on some button on the sidebar, eg `Send XStream`. looks like the error comes in one of the hooks
image


Both of these should be a quick fix, and push the code in the same PR once you are done.

**Comment by abhik-99** [comment]
Latest commit solves these errors. Changes done:
1. Exposed Streams through a Provider
2. Added Margin on Custom Button for wallet connection.

**Comment by aditya172926** [comment]
The UI issue is solved.
The second issue fix has introduced a new bug. On clicking the `Send XStream` or `Notifications` button I don't get an error, but it doesn't redirect me to that page as well.
@abhik-99 on clicking the buttons on the sidebar, I should be able to go to that page.

The functionality shouldn't change even after you have refactored the code.
Do the following fixes and we will be scheduling your next final call after that.

**Comment by abhik-99** [comment]
Solved.

**Comment by aditya172926** [comment]
LGTM 👍

**Pull request closed without merging**
